name = input("Enter name: ")
branch = input("Enter your branch: ")
gender = input("Enter your gender: ")
college = input("Enter your college: ")
age = int(input("Enter your age: "))
print("Name: ",name)
print("Branch: ",branch)
print("Gender: ",gender)
print("College Name: ",college)
print("Age: ",age)
